# Generated by Django 5.0.4 on 2024-05-01 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "Car", "verbose_name_plural": "Cars"},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ("name",), "verbose_name_plural": "Manufacturers"},
        ),
        migrations.AlterField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(
                related_name="cars", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="taxi.manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="driver",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
