# Generated by Django 5.0.4 on 2024-05-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "car", "verbose_name_plural": "cars"},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "driver", "verbose_name_plural": "drivers"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ("name",), "verbose_name_plural": "manufacturers"},
        ),
    ]
